config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  #devise_for :users

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :chat_rooms, only: [:new, :create, :show, :index]

#  root 'chat_rooms#index'
  root 'pages#index'

  #Show all tables
  get '/tables', to: 'pages#tables'

  #Get menu items
  get '/get_menu', to: 'api/items#get_menu'

  post '/change_pin', to: 'api/chat_rooms#change_pin'
  post '/check_pin', to: 'chat_rooms#check_pin'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  # In this callback self is a saved message
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy


  def name
    email.split('@')[0]
  end
end

app/controllers/api/chat_rooms_controller.rb
class Api::ChatRoomsController < ApplicationController
  def index
      chat_rooms = ChatRoom.all
      render json: chat_rooms.to_json

  end

  def check_pin
    chat_room = ChatRoom.find_by( pin: params[:pin] )

    if !chat_room
      render json: 'false'.to_json
    else
      redirect_to :controller => 'chat_rooms',
      :action => 'show',
      :id => chat_room.id, #chat_room id
      :user_id => '2',
      :found => "success"
    end
  end

  def change_pin
    #find the selected chat room in the DB
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:table_id])
    #all messages from this chat_room
    @messages = @chat_room.messages

    # Delete all previous messages from chat room
    @messages.each do |message|
      message.destroy
    end

    # create a new pin
    @chat_room.pin = Array.new(5){rand(36).to_s(36)}.join

    #Save info
    @chat_room.save

    #return pin as JSON data
    render json: @chat_room.pin.to_json
  end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:get_menu]
  def get_menu
      all_items = Item.all
      @breakfast = Item.where(category: 'breakfast')
      @lunch = Item.where(category: 'lunch')
      @desert = Item.where(category: 'desert')
      @beer = Item.where(category: 'beer')
      @wine = Item.where(category: 'wine')
      @coffee = Item.where(category: 'coffee')
      render json: all_items.to_json
  end

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  def check_messages
      quantity = Messages.where(chat_room_id: params[:chat_room_id]).count
      render json: quantity.to_json
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chat_room_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:check_pin]

  def index
    @chat_rooms = ChatRoom.all
  end


  def new
    @chat_room = ChatRoom.new
  end


  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end


  def show
    room = ChatRoom.find_by(id: params[:id])
    if current_user.user_type == 'admin' || room.pin == params[:pin]
      @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
      #Messages to be rendered are only the ones created after user enter room
      @messages = @chat_room.messages #.where(created_at: Time.now..Time.now)
      @message = Message.new
    else
      redirect_to root_path
    end
  end


  def check_pin
    chat_room = ChatRoom.find_by( pin: params[:pin] )
    if !chat_room
      flash[:danger] = "PIN code invalid, try again"
      redirect_to root_path
    else
      sign_in(User.find('2'), scope: :user)
      redirect_to :controller => 'chat_rooms',
      :action => 'show',
      :id => chat_room.id, #chat_room id
      :pin => params[:pin]
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end

  def tables
    @tables = ChatRoom.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end


  def get_breakfast
    @breakfast = Item.where(category: 'breakfast')
  end

  def get_lunch
    @lunch = Item.where(category: 'lunch')
  end

  def get_desert
    @desert = Item.where(category: 'desert')
  end

  def get_beer
    @beer = Item.where(category: 'beer')
  end

  def get_wine
    @wine = Item.where(category: 'wine')
  end

  def get_coffee
    @coffee = Item.where(category: 'coffee')
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li class="list-icon" id="<%= chat_room.id %>">

  <div class="slot table-title">Table - <%=  chat_room.id %></div>

  <div class="slot">
    <button type="button" class="btn btn-default" aria-label="Left Align">
      <i class="fa fa-comment" id="chat-<%= chat_room.id %>"></i>
      <%= link_to 'Chat', chat_room_path(chat_room) %>
    </button>
  </div>

  <div class="slot">
    <button type="button" class="btn-key btn btn-default" aria-label="Left Align">
      <i class="fa fa-key"></i> Generate Code
    </button>
  </div>

  <div class="slot pin"><%= chat_room.pin %></div>
</li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<% if current_user.user_type == "admin" %>
<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>
<ul>
  <%= render @chat_rooms %>
</ul>
<% end  %>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<% if current_user.user_type == "admin" %>
  <%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
  <% end %>
<% elsif %>
  <h2>You have no privileges to create a new chat room</h2>
<% end %>

app/views/chat_rooms/show.html.erb
<section id="chat-window" class="">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center chat-msg-panel">
              <h2><%= @chat_room.title %></h2>

               <!-- providing the room’s id -->
              <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
                <%= render @messages %>
              </div>


              <!-- New Message -->
              <%= form_for @message, url: '#' do |f| %>

                <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
                <div class="col-xs-10 form-group msgbox">

                  <%= f.text_field :body,
                                  class: 'form-control',
                                  rows: 2,
                                  placeholder: 'Type your message...' %>

                </div>
                <div class="col-xs-2 sendbtn">
                  <%= f.submit "Send", class: 'btn btn-warning'%>
                </div>
              <% end %>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div id='flash' class='alert alert-<%="#{name}"%> text-center'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_links.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<meta name="description" content="">
<meta name="author" content="">

<title>Order App</title>

<!-- Custom Fonts -->
<!-- <link href="../assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Coming+Soon" rel="stylesheet">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_navbar.html.erb
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand logged-user">
          <a href="/#top" onclick=$("#menu-close").click();>Home</a>
        </li>
        <% if user_signed_in? %>
          <li>
            Logged in as <%= current_user.username.upcase %>
          </li>
        <% end %>

        <% if user_signed_in? && current_user.user_type == 'admin' %>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :onclick => "$('#menu-close').click()" %>
          </li>
          <li>
              <a href="/tables" onclick=$("#menu-close").click();>Tables</a>
          </li>
          <li>
            <%= link_to 'Create chat room', new_chat_room_path , :onclick => "$('#menu-close').click()"%>
          </li>
        <% end %>
        <li>
            <a href="/#top" onclick=$("#menu-close").click();>Home</a>
        </li>

        <li id="restaurant-menu">
            <a href="#" onclick=$("#menu-close").click();>Food and Drinks Menu</a>
        </li>
        <li>
            <a href="/#contact" onclick=$("#menu-close").click();>Contact</a>
        </li>

    </ul>
</nav>

app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
  });

  $( '.btn-key' ).click(function(event) {
    event.preventDefault();  // Prevent the button to send the form
    var id = $(this).closest('li').attr('id');
    var options = { // Details to connect to the server
      url: '/change_pin',
      method: 'post',
      data: { table_id: $(this).closest('li').attr('id') }
    }

    var show_pin = function(response) { // function that
      //look up for right id and write response
      $('#'+id).find('.pin').text(response)
    }

    $.ajax(options).done(show_pin);
  });

  // Select menu
  $('#restaurant-menu').click(function () {
    $('#house-menu').show();

    event.preventDefault();  // Prevent the button to send the form

    var options = { // Details to connect to the server
      url: '/get_menu',
      method: 'get',
    }

    var show_items = function(response) { // Show menu items

     $('#'+id).find('.pin').text(response)
    }

    $.ajax(options).done(show_items);

  });

  // Close restaurant menu
  $("#close-house-menu").click(function () {
    $('#house-menu').hide();
  })

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Order App</title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/links' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'pages/menu' %>
      <%= render 'layouts/navbar' %>

      <%= yield %>

      <%= render 'layouts/scripts' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">

      <!-- User image -->
      <div class="card-image col-md-2">
        <%= gravatar_for message.user %>
        <span class="text-muted msgheader"><%= message.user.name %> at <%= message.timestamp %>:</span><br>

      </div>

      <!-- Text -->
      <div class="col-md-10">

        <!-- Message metadata -->

        <!-- Message body -->
        <p class="card-text">
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_menu.html.erb
<div id="house-menu" class="house-menu" >
  <i id="close-house-menu" class="fa fa-remove fa-fw fa-3x"></i>

  <h1 class="text-center">MENU</h1>

  <div id="food" class="food">
    <h2 class="text-center">Meals</h2>
    <div id="breakfast" class="breakfast">
      <h3 class="text-center">Breakfast</h3>
      <% get_breakfast.each do |item| %>
        <%= raise issue %>
      <% end %>
    </div>
    <div id="lunch" class="lunch">
      <h3 class="text-center">Lunch</h3>
    </div>
    <div id="desert" class="desert">
      <h3 class="text-center">Desert</h3>
    </div>
  </div> <!-- Meals -->

  <div id="drinks" class="drinks">
    <h2 class="text-center">Drinks</h2>
    <div id="beer" class="beer">
      <h3 class="text-center">Beer</h3>
    </div>

    <div id="wine" class="wine">
      <h3 class="text-center">Wine</h3>
    </div>

    <div id="coffee" class="coffee">
      <h3 class="text-center">Hot Drinks</h3>
    </div>

  </div> <!-- drinks  -->

</div> <!-- house-menu  -->

app/views/pages/_pin.hmtl.erb
<%= form_tag('/check_pin') do %>
  <label id="pin-label">Enter PIN here!</label>
  <input id="pin-code" type="text" name="pin" value="">
  <%= submit_tag("Enter", :id => "check-pin-btn") %>
<% end %>

app/views/pages/_table_chatrooms.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/pages/index.html.erb
<!-- Header -->
<header id="top" class="header">
  <div class="header-layer">
    <div class="text-vertical-center top-title">
        <h1>My Restaurant App</h1>
        <h3>Make your order in-house via chat</h3>
        <br>
    </div>
  </div>
</header>

<!-- About -->
<section id="app-code" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>In-house Order!</h2>
                <p class="lead">Take your time! <br> Check the menu and order from your phone.</p>
                <%= form_tag('/check_pin') do %>

                  <input id="pin-code" type="text" name="pin" value="" placeholder="Enter PIN here!">
                  <%= submit_tag("Enter", :id => "check-pin-btn") %>
                <% end %>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Services -->
<!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
<!-- <section id="services" class="services bg-primary">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>Our Services</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Breakfast</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-compass fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Lunch</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-flask fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-shield fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</section>
-->

<!-- Callout -->
<aside class="callout">
    <div class="text-vertical-center callout-layer">
        <h1>Best Coffee in Melbourne</h1>
    </div>
</aside>

<!-- Portfolio -->
<section id="portfolio" class="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h2>Delicious meals and desserts</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-6">
                        <div class="portfolio-item">

                              <%= image_tag('Smashed Avo' , :class => "img-portfolio img-responsive") %>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="portfolio-item">
                          <%= image_tag('croquette' , :class => "img-portfolio img-responsive") %>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="portfolio-item">
                          <%= image_tag('bananabread' , :class => "img-portfolio img-responsive") %>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="portfolio-item">
                          <%= image_tag('tiramissu' , :class => "img-portfolio img-responsive") %>
                        </div>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Call to Action -->
<aside id="open-hours" class="call-to-action bg-primary">
    <div class="container">
        <div class="row">
            <div  class="col-lg-12 text-center">
                <h3>Open hours:</h3>
                <ul class="open-hours">
                  <li>Mon - Fri</li>
                  <li>7am - 4pm</li>
                </ul>
                <ul class="open-hours">
                  <li>Sat - Sun</li>
                  <li>7am - 4pm</li>
                </ul>

            </div>
        </div>
    </div>
</aside>

<!-- Map -->
<section id="contact" class="map">
    <!-- <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
   -->
    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6303.665639256836!2d144.95535362791676!3d-37.81738468513806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b33fa08005%3A0x5b4ce751bc4d46f6!2sGeneral+Assembly+Melbourne!5e0!3m2!1sen!2sau!4v1484563119970"></iframe>

    <br />
    <small>
        <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6303.665639256836!2d144.95535362791676!3d-37.81738468513806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b33fa08005%3A0x5b4ce751bc4d46f6!2sGeneral+Assembly+Melbourne!5e0!3m2!1sen!2sau!4v1484563119970"></a>
    </small>

</section>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h4><strong>Pedro Araujo</strong>
                </h4>
                <p>Web Developer
                    <br>Melbourne - VIC</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-phone fa-fw"></i> 0497 853 085</li>
                    <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:pptaraujo@gmail.com">pptaraujo@gmail.com</a>
                    </li>
                </ul>
                <br>
                <ul class="list-inline">
                    <li>
                        <a href="https://www.facebook.com/pptaraujo"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="https://github.com/ppteixeira"><i class="fa fa-github fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="https://au.linkedin.com/in/pedro-araujo"><i class="fa fa-linkedin fa-fw fa-3x"></i></a>
                    </li>
                </ul>
                <hr class="small">
                <!-- <p class="text-muted">Copyright &copy; Your Website 2014</p> -->
            </div>
        </div>
    </div>
    <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
</footer>

<!-- Custom Theme JavaScript -->

app/views/pages/tables.html.erb
<section id="tables-page" class="tables">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center table-list">
                <h1>Tables</h1>
                <ul class="">
                  <%= render @tables.order('id ASC') %>
                </ul>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>